import type { HasSsg } from "quasar";
import type { RouteRecordRaw } from "vue-router";

import type { QSsrContext, RenderVueParams } from "../ssr/ssrcontext.d.ts";
import type { QuasarContext } from "../configuration/context.d.ts";
import type { QuasarSsgConfiguration } from "../configuration/ssg-conf.js";

export type HasSsgParam = HasSsg<{ ssrContext?: QSsrContext | null }>;

export interface SsgPage {
  /**
   * The vue-router route to render.
   * It must be a valid route in your Vue Router configuration.
   */
  route: string;

  /**
   * The original Vue Router route object.
   */
  vueRouterRoute?: RouteRecordRaw;

  /**
   * Optional label to identify the SSG page in logs.
   */
  label?: string;

  /**
   * Optional directory to place the generated HTML file in.
   * Must use relative path to the dist folder.
   * It will be joined with the quasar.config > build > distDir.
   * If not provided, the route will be used to determine the directory.
   */
  dir?: string;

  /**
   * Optional filename to use for the generated HTML file.
   * @default 'index.html'
   */
  filename?: string;

  /**
   * Optional SSR context to use when rendering the specific page.
   * If omitted, the default SSR context is used. One important prop
   * for it is `req`, which has the IncomingMessage native node:http
   * type. Gets merged into the ssrContext so you don't have to
   * define all its props.
   *
   * @type QSsrContext {@link QSsrContext}
   */
  ssrContext?: QSsrContext;
}

interface SsgRenderPreloadTagCallbackOptions {
  ssrContext: RenderVueParams;
}

export type SsgRenderPreloadTagCallback = (
  file: string,
  options: SsgRenderPreloadTagCallbackOptions
) => string;

export type SsgParseVueRouterParams = {
  /**
   * Vue Router routes definition to parse.
   */
  routes: RouteRecordRaw[];

  /**
   * Optional parent path to use for these routes.
   * @default '/'
   */
  parentPath?: string;

  /**
   * Optional flag to enable verbose logging.
   * If true, it will log the ignored routes with dynamic parameters.
   * @default false
   */
  verbose?: boolean;
};

export type SsgParseVueRouterResult = {
  ssgPages: SsgPage[];
  hasIgnoredRoutes: boolean;
  ignoredRedirectingRoutes: RouteRecordRaw[];
  ignoredDynamicRoutes: RouteRecordRaw[];
  ignoredCsrRoutes: RouteRecordRaw[];
};

export type SsgParseVueRouterRoutes = (
  params: SsgParseVueRouterParams
) => SsgParseVueRouterResult;

export type SsgGetFilenameBasedRoutes = () => Promise<RouteRecordRaw[]>;

export interface SsgGetPagesParams {
  /**
   * The Quasar build context.
   * Same as the one from your /quasar.config file. You can use this to
   * access ctx.appPaths (among other things) to resolve paths to your
   * pages, which is especially useful if you are using tools like
   * tinyglobby to manually read your file system.
   *
   * @type QuasarContext {@link QuasarContext}
   */
  readonly ctx: QuasarContext;

  /**
   * The Quasar SSG configuration (quasar.config file > ssg)
   * @type QuasarSsgConfiguration {@link QuasarSsgConfiguration}
   */
  readonly quasarConfSsg: QuasarSsgConfiguration;

  /**
   * A built-in helper function that parses your Vue Router routes
   * and automatically builds a list of routes to generate.
   * It will ignore redirects, routes with params, and CSR defined routes.
   * You will need to define and add those SSG pages manually, should you want.
   *
   * @param {SsgParseVueRouterParams} options - The configuration object. {@link SsgParseVueRouterParams}
   * @param {RouteRecordRaw[]} options.routes - Vue Router routes definition to parse. {@link RouteRecordRaw}
   * @param {string} [options.parentPath='/'] - Optional parent path to use for these routes.
   * @param {boolean} [options.verbose=false] - Optional flag to enable verbose logging. If true, it logs ignored routes with dynamic parameters.
   * @returns {SsgParseVueRouterResult} {@link SsgParseVueRouterResult}
   */
  parseVueRouterRoutes: SsgParseVueRouterRoutes;

  /**
   * Helper to get the filename-based routes auto-generated by Vue Router.
   * Can be used only when quasar.config > build > filenameBasedRouting is set to true.
   *
   * @returns {Promise<RouteRecordRaw[]>} Array of Vue Router routes. {@link RouteRecordRaw}
   */
  getFilenameBasedRoutes: SsgGetFilenameBasedRoutes;
}

export type SsgGetPagesCallback = (
  params: SsgGetPagesParams
) => SsgPage[] | Promise<SsgPage[]>;
