os: osx
osx_image: xcode8.3
sudo: false
language: node_js
node_js: '8'
env:
  global:
    - HOMEBREW_NO_AUTO_UPDATE=1
    - USE_SDK_WRAPPER=true
    - ANDROID_HOME=/usr/local/share/android-sdk
    - ANDROID_NDK_HOME=/usr/local/share/android-ndk
    - ANDROID_SDK_ROOT=/usr/local/share/android-sdk
    - WINEDLLOVERRIDES="mscoree,mshtml="
    - WINEDEBUG="-all"
cache:
  directories:
    - node_modules
    - "$HOME/.npm/_prebuilds"
    - "$HOME/.cache/yarn"
    - "$HOME/Library/Caches/Homebrew"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.10.1
  - export PATH="$HOME/.yarn/bin:$PATH"
  - npm install wine-darwin@1.9.17-1
  - yarn wine hostname
  - brew install ant gradle
  - npm install -g cordova ios-deploy pnpm
install:
  - pnpm recursive install
script:
  - pnpm recursive test