packages:
  - app-vite
  - app-webpack
  - vite-plugin
  - vite-plugin/playground
  - extras
  - ui
  - ui/playground
  - ui/testing
  - create-quasar
  - cli
  - docs
  - utils/render-ssr-error
  - utils/ssl-certificate

# The packages below are not included. Use their individual folders.
# - icongenie
# - utils/babel-preset-app
# - utils/ssr-helpers

onlyBuiltDependencies:
  - '@parcel/watcher'
  - core-js
  - electron-winstaller
  - esbuild
  - lightningcss
  - unrs-resolver
