export default {
  components: [
    // "QAvatar",
    // "QBtn",
    // "QCard",
    // "QCardActions",
    // "QCardSection",
    // "QCheckbox",
    // "QChip",
    // "QDrawer",
    // "QDialog",
    // "QExpansionItem",
    // "QHeader",
    // "QFooter",
    // "QIcon",
    // "QImg",
    // "QInput",
    // "QItem",
    // "QItemSection",
    // "QItemLabel",
    // "QLayout",
    // "QLinearProgress",
    // "QList",
    // "QPage",
    // "QPageContainer",
    // "QPageScroller",
    // "QSelect",
    // "QStep",
    // "QStepper",
    // "QStepperNavigation",
    // "QToolbar",
    // "QToolbarTitle",
  ],
  directives: [
    "ClosePopup",
    "Ripple",
  ],
  css: [
    "@wywm/ao/css",
  ],
};
