/**
 * DO NOT EDIT THIS FILE. It is automatically generated
 * from its .mjs counterpart (same filename but with .mjs extension).
 * Edit that file instead (fontawesome-v6.mjs).
 */
module.exports = {
  name: 'fontawesome-v6',
  type: {
    positive: 'fas fa-check',
    negative: 'fas fa-triangle-exclamation',
    info: 'fas fa-circle-info',
    warning: 'fas fa-exclamation'
  },
  arrow: {
    up: 'fas fa-arrow-up',
    right: 'fas fa-arrow-right',
    down: 'fas fa-arrow-down',
    left: 'fas fa-arrow-left',
    dropdown: 'fas fa-caret-down'
  },
  chevron: {
    left: 'fas fa-chevron-left',
    right: 'fas fa-chevron-right'
  },
  colorPicker: {
    spectrum: 'fas fa-eye-dropper',
    tune: 'fas fa-sliders',
    palette: 'fas fa-swatchbook'
  },
  pullToRefresh: {
    icon: 'fas fa-rotate'
  },
  carousel: {
    left: 'fas fa-chevron-left',
    right: 'fas fa-chevron-right',
    up: 'fas fa-chevron-up',
    down: 'fas fa-chevron-down',
    navigationIcon: 'fas fa-circle'
  },
  chip: {
    remove: 'fas fa-circle-xmark',
    selected: 'fas fa-check'
  },
  datetime: {
    arrowLeft: 'fas fa-chevron-left',
    arrowRight: 'fas fa-chevron-right',
    now: 'far fa-clock',
    today: 'far fa-calendar-check'
  },
  editor: {
    bold: 'fas fa-bold',
    italic: 'fas fa-italic',
    strikethrough: 'fas fa-strikethrough',
    underline: 'fas fa-underline',
    unorderedList: 'fas fa-list-ul',
    orderedList: 'fas fa-list-ol',
    subscript: 'fas fa-subscript',
    superscript: 'fas fa-superscript',
    hyperlink: 'fas fa-link',
    toggleFullscreen: 'fas fa-maximize',
    quote: 'fas fa-quote-right',
    left: 'fas fa-align-left',
    center: 'fas fa-align-center',
    right: 'fas fa-align-right',
    justify: 'fas fa-align-justify',
    print: 'fas fa-print',
    outdent: 'fas fa-outdent',
    indent: 'fas fa-indent',
    removeFormat: 'fas fa-eraser',
    formatting: 'fas fa-heading',
    fontSize: 'fas fa-text-height',
    align: 'fas fa-align-left',
    hr: 'far fa-square-minus',
    undo: 'fas fa-rotate-left',
    redo: 'fas fa-rotate-right',
    heading: 'fas fa-heading',
    code: 'fas fa-code',
    size: 'fas fa-text-height',
    font: 'fas fa-font',
    viewSource: 'fas fa-code'
  },
  expansionItem: {
    icon: 'fas fa-chevron-down',
    denseIcon: 'fas fa-caret-down'
  },
  fab: {
    icon: 'fas fa-plus',
    activeIcon: 'fas fa-xmark'
  },
  field: {
    clear: 'fas fa-circle-xmark',
    error: 'fas fa-circle-exclamation'
  },
  pagination: {
    first: 'fas fa-backward-step',
    prev: 'fas fa-chevron-left',
    next: 'fas fa-chevron-right',
    last: 'fas fa-forward-step'
  },
  rating: {
    icon: 'fas fa-star'
  },
  stepper: {
    done: 'fas fa-check',
    active: 'fas fa-pencil',
    error: 'fas fa-triangle-exclamation'
  },
  tabs: {
    left: 'fas fa-chevron-left',
    right: 'fas fa-chevron-right',
    up: 'fas fa-chevron-up',
    down: 'fas fa-chevron-down'
  },
  table: {
    arrowUp: 'fas fa-arrow-up',
    warning: 'fas fa-triangle-exclamation',
    firstPage: 'fas fa-backward-step',
    prevPage: 'fas fa-chevron-left',
    nextPage: 'fas fa-chevron-right',
    lastPage: 'fas fa-forward-step'
  },
  tree: {
    icon: 'fas fa-play'
  },
  uploader: {
    done: 'fas fa-check',
    clear: 'fas fa-xmark',
    add: 'fas fa-square-plus',
    upload: 'fas fa-upload',
    removeQueue: 'fas fa-bars-staggered',
    removeUploaded: 'fas fa-clipboard-check'
  }
}
