
/*
 * Do not edit this file. It is automatically generated
 * from its webfont counterpart (same filename without "svg-" prefix).
 * Edit that file instead (themify.js).
 */


import {
  tiCheck,
  tiAlert,
  tiInfoAlt,
  tiArrowUp,
  tiArrowRight,
  tiArrowDown,
  tiArrowLeft,
  tiArrowCircleDown,
  tiAngleLeft,
  tiAngleRight,
  tiBrushAlt,
  tiPanel,
  tiPalette,
  tiReload,
  tiAngleUp,
  tiAngleDown,
  tiControlRecord,
  tiLayoutSliderAlt,
  tiClose,
  tiTime,
  tiCalendar,
  tiItalic,
  tiUnderline,
  tiList,
  tiListOl,
  tiLink,
  tiFullscreen,
  tiQuoteRight,
  tiAlignLeft,
  tiAlignCenter,
  tiAlignRight,
  tiAlignJustify,
  tiPrinter,
  tiAngleDoubleLeft,
  tiAngleDoubleRight,
  tiText,
  tiSmallcap,
  tiMinus,
  tiShareAlt,
  tiShare,
  tiParagraph,
  tiShortcode,
  tiPlus,
  tiStar,
  tiPencil,
  tiControlPlay,
  tiSupport,
  tiCloudUp,
  tiLayoutMediaRight,
  tiLayoutPlaceholder
} from '@quasar/extras/themify'

// there are some icons that are needed but not available
// so we import them from MDI as svgs

import {
  mdiFormatBold,
  mdiFormatStrikethroughVariant,
  mdiFormatSubscript,
  mdiFormatSuperscript,
  mdiFormatClear,
  mdiFormatHeader1,
  mdiFormatHeader2,
  mdiFormatHeader3,
  mdiFormatHeader4,
  mdiFormatHeader5,
  mdiFormatHeader6,
  mdiCodeTags,
  mdiNumeric1Box,
  mdiNumeric2Box,
  mdiNumeric3Box,
  mdiNumeric4Box,
  mdiNumeric5Box,
  mdiNumeric6Box,
  mdiNumeric7Box,
  mdiFormatFont
} from '@quasar/extras/mdi-v6'



export default {
  name: 'svg-themify',
  type: {
    positive: tiCheck,
    negative: tiAlert,
    info: tiInfoAlt,
    warning: tiAlert
  },
  arrow: {
    up: tiArrowUp,
    right: tiArrowRight,
    down: tiArrowDown,
    left: tiArrowLeft,
    dropdown: tiArrowCircleDown
  },
  chevron: {
    left: tiAngleLeft,
    right: tiAngleRight
  },
  colorPicker: {
    spectrum: tiBrushAlt,
    tune: tiPanel,
    palette: tiPalette
  },
  pullToRefresh: {
    icon: tiReload
  },
  carousel: {
    left: tiAngleLeft,
    right: tiAngleRight,
    up: tiAngleUp,
    down: tiAngleDown,
    navigationIcon: tiControlRecord,
    thumbnails: tiLayoutSliderAlt
  },
  chip: {
    remove: tiClose,
    selected: tiCheck
  },
  datetime: {
    arrowLeft: tiAngleLeft,
    arrowRight: tiAngleRight,
    now: tiTime,
    today: tiCalendar
  },
  editor: {
    italic: tiItalic,
    underline: tiUnderline,
    unorderedList: tiList,
    orderedList: tiListOl,
    hyperlink: tiLink,
    toggleFullscreen: tiFullscreen,
    quote: tiQuoteRight,
    left: tiAlignLeft,
    center: tiAlignCenter,
    right: tiAlignRight,
    justify: tiAlignJustify,
    print: tiPrinter,
    outdent: tiAngleDoubleLeft,
    indent: tiAngleDoubleRight,
    formatting: tiText,
    fontSize: tiSmallcap,
    align: tiAlignLeft,
    hr: tiMinus,
    undo: tiShareAlt,
    redo: tiShare,
    heading: tiParagraph,
    size: tiSmallcap,
    viewSource: tiShortcode,

    bold: mdiFormatBold,
    strikethrough: mdiFormatStrikethroughVariant,
    subscript: mdiFormatSubscript,
    superscript: mdiFormatSuperscript,
    removeFormat: mdiFormatClear,
    heading1: mdiFormatHeader1,
    heading2: mdiFormatHeader2,
    heading3: mdiFormatHeader3,
    heading4: mdiFormatHeader4,
    heading5: mdiFormatHeader5,
    heading6: mdiFormatHeader6,
    code: mdiCodeTags,
    size1: mdiNumeric1Box,
    size2: mdiNumeric2Box,
    size3: mdiNumeric3Box,
    size4: mdiNumeric4Box,
    size5: mdiNumeric5Box,
    size6: mdiNumeric6Box,
    size7: mdiNumeric7Box,
    font: mdiFormatFont
  },
  expansionItem: {
    icon: tiAngleDown,
    denseIcon: tiArrowCircleDown
  },
  fab: {
    icon: tiPlus,
    activeIcon: tiClose
  },
  field: {
    clear: tiClose,
    error: tiAlert
  },
  pagination: {
    first: tiAngleDoubleLeft,
    prev: tiAngleLeft,
    next: tiAngleRight,
    last: tiAngleDoubleRight
  },
  rating: {
    icon: tiStar
  },
  stepper: {
    done: tiCheck,
    active: tiPencil,
    error: tiAlert
  },
  tabs: {
    left: tiAngleLeft,
    right: tiAngleRight,
    up: tiAngleUp,
    down: tiAngleDown
  },
  table: {
    arrowUp: tiArrowUp,
    warning: tiAlert,
    firstPage: tiAngleDoubleLeft,
    prevPage: tiAngleLeft,
    nextPage: tiAngleRight,
    lastPage: tiAngleDoubleRight
  },
  tree: {
    icon: tiControlPlay
  },
  uploader: {
    done: tiCheck,
    clear: tiClose,
    add: tiSupport,
    upload: tiCloudUp,
    removeQueue: tiLayoutMediaRight,
    removeUploaded: tiLayoutPlaceholder
  }
}
