
/*
 * Do not edit this file. It is automatically generated
 * from its webfont counterpart (same filename without "svg-" prefix).
 * Edit that file instead (themify.js).
 */

import {
  matFormatBold,
  matStrikethroughS,
  matVerticalAlignBottom,
  matVerticalAlignTop,
  matFormatClear,
  matCode,
  matFontDownload
} from '@quasar/extras/material-icons'

import {
  tiCheck,
  tiAlert,
  tiInfoAlt,
  tiArrowUp,
  tiArrowRight,
  tiArrowDown,
  tiArrowLeft,
  tiArrowCircleDown,
  tiAngleLeft,
  tiAngleRight,
  tiBrushAlt,
  tiPanel,
  tiPalette,
  tiReload,
  tiControlRecord,
  tiLayoutSliderAlt,
  tiClose,
  tiTime,
  tiCalendar,
  tiItalic,
  tiUnderline,
  tiList,
  tiListOl,
  tiLink,
  tiFullscreen,
  tiQuoteRight,
  tiAlignLeft,
  tiAlignCenter,
  tiAlignRight,
  tiAlignJustify,
  tiPrinter,
  tiAngleDoubleLeft,
  tiAngleDoubleRight,
  tiText,
  tiSmallcap,
  tiMinus,
  tiShareAlt,
  tiShare,
  tiParagraph,
  tiShortcode,
  tiAngleDown,
  tiPlus,
  tiStar,
  tiPencil,
  tiAngleUp,
  tiControlPlay,
  tiSupport,
  tiCloudUp,
  tiLayoutMediaRight,
  tiLayoutPlaceholder
} from '@quasar/extras/themify'

export default {
  name: 'svg-themify',
  type: {
    positive: tiCheck,
    negative: tiAlert,
    info: tiInfoAlt,
    warning: tiAlert
  },
  arrow: {
    up: tiArrowUp,
    right: tiArrowRight,
    down: tiArrowDown,
    left: tiArrowLeft,
    dropdown: tiArrowCircleDown
  },
  chevron: {
    left: tiAngleLeft,
    right: tiAngleRight
  },
  colorPicker: {
    spectrum: tiBrushAlt,
    tune: tiPanel,
    palette: tiPalette
  },
  pullToRefresh: {
    icon: tiReload
  },
  carousel: {
    left: tiAngleLeft,
    right: tiAngleRight,
    navigationIcon: tiControlRecord,
    thumbnails: tiLayoutSliderAlt
  },
  chip: {
    remove: tiClose,
    selected: tiCheck
  },
  datetime: {
    arrowLeft: tiAngleLeft,
    arrowRight: tiAngleRight,
    now: tiTime,
    today: tiCalendar
  },
  editor: {
    bold: matFormatBold,
    italic: tiItalic,
    strikethrough: matStrikethroughS,
    underline: tiUnderline,
    unorderedList: tiList,
    orderedList: tiListOl,
    subscript: matVerticalAlignBottom,
    superscript: matVerticalAlignTop,
    hyperlink: tiLink,
    toggleFullscreen: tiFullscreen,
    quote: tiQuoteRight,
    left: tiAlignLeft,
    center: tiAlignCenter,
    right: tiAlignRight,
    justify: tiAlignJustify,
    print: tiPrinter,
    outdent: tiAngleDoubleLeft,
    indent: tiAngleDoubleRight,
    removeFormat: matFormatClear,
    formatting: tiText,
    fontSize: tiSmallcap,
    align: tiAlignLeft,
    hr: tiMinus,
    undo: tiShareAlt,
    redo: tiShare,
    heading: tiParagraph,
    code: matCode,
    size: tiSmallcap,
    font: matFontDownload,
    viewSource: tiShortcode
  },
  expansionItem: {
    icon: tiAngleDown,
    denseIcon: tiArrowCircleDown
  },
  fab: {
    icon: tiPlus,
    activeIcon: tiClose
  },
  field: {
    clear: tiClose,
    error: tiAlert
  },
  pagination: {
    first: tiAngleDoubleLeft,
    prev: tiAngleLeft,
    next: tiAngleRight,
    last: tiAngleDoubleRight
  },
  rating: {
    icon: tiStar
  },
  stepper: {
    done: tiCheck,
    active: tiPencil,
    error: tiAlert
  },
  tabs: {
    left: tiAngleLeft,
    right: tiAngleRight,
    up: tiAngleUp,
    down: tiAngleDown
  },
  table: {
    arrowUp: tiArrowUp,
    warning: tiAlert,
    prevPage: tiAngleLeft,
    nextPage: tiAngleRight
  },
  tree: {
    icon: tiControlPlay
  },
  uploader: {
    done: tiCheck,
    clear: tiClose,
    add: tiSupport,
    upload: tiCloudUp,
    removeQueue: tiLayoutMediaRight,
    removeUploaded: tiLayoutPlaceholder
  }
}
