import type { RolldownOptions } from "rolldown";
import type { GenerateSWOptions, InjectManifestOptions } from "workbox-build";
import type { RouteRecordRaw } from "vue-router";

import type { QSsrContext } from "../ssr/ssrcontext.d.ts";

interface QuasarSsrManifest {
  [key: string]: string[];
}

export interface SsgPage {
  /**
   * The vue-router route to render.
   * It must be a valid route in your Vue Router configuration.
   */
  route: string;

  /**
   * The original Vue Router route object.
   */
  vueRouterRoute?: RouteRecordRaw;

  /**
   * Optional label to identify the SSG page in logs.
   */
  label?: string;

  /**
   * Optional directory to place the generated HTML file in.
   * Must use relative path to the dist folder.
   * It will be joined with the quasar.config > build > distDir.
   * If not provided, the route will be used to determine the directory.
   */
  dir?: string;

  /**
   * Optional filename to use for the generated HTML file.
   * @default 'index.html'
   */
  filename?: string;

  /**
   * Optional SSR context to use when rendering the specific page.
   * If omitted, the default SSR context is used. One important prop
   * for it is `req`, which has the IncomingMessage native node:http
   * type. Gets merged into the ssrContext so you don't have to
   * define all its props.
   *
   * @type QSsrContext {@link QSsrContext}
   */
  ssrContext?: QSsrContext;

  /**
   * Callback function that is called after rendering the SSG page.
   * You can use this to optionally modify the generated HTML content
   * before it is written to disk.
   *
   * If you return a string, it will replace the generated HTML content.
   * If you don't return anything, the generated HTML content will be used as-is.
   *
   * Example usage:
   * transformHtml: html => "<!-- This HTML was generated by Quasar SSG -->\n" + html
   *
   * @param {string} html - The rendered HTML content for the SSG page.
   * @returns {string | Promise<string> | void | Promise<void>} The modified HTML content or void.
   */
  transformHtml?: (
    html: string
  ) => string | Promise<string> | void | Promise<void>;
}

export interface OnSsgRendererErrorFunctionParams {
  /**
   * The error object that was thrown during the SSG rendering process.
   */
  err: Error;

  /**
   * The extra reason for the error, if available.
   * This can provide additional context about why the error occurred.
   */
  reason?: string;

  /**
   * The SSG page that was being rendered when the error occurred.
   * @type SsgPage {@link SsgPage}
   */
  ssgPage: SsgPage;
}
export type OnSsgRendererErrorFunction = (
  params: OnSsgRendererErrorFunctionParams
) => void | Promise<void>;

export type OnSsgRendererError =
  | "abort"
  | "error"
  | "warn"
  | "ignore"
  | OnSsgRendererErrorFunction;

/**
 * Properties also available in the SSR configuration inherit their explicitly
 * configured SSR value when omitted here. An SSG value always takes precedence.
 */
export interface QuasarSsgConfiguration {
  /**
   * Defines how to handle errors encountered during the SSG rendering process.
   *
   * Possible values:
   *  - "abort": Immediately halts the build process on the first error.
   *  - "error": Accumulates all errors and fails the build at the end.
   *  - "warn": Logs the errors to the console, but the build finishes successfully.
   *  - "ignore": Silently ignores errors with a single warning at the end
   *              with how many pages failed to render.
   *  - A custom function to implement your own error handling logic.
   *
   * @example
   * onSsgRendererError: ({ err, reason, ssgPage }) => {
   *   const pageId = `${ssgPage.route} ${ssgPage.label ? ` (${ssgPage.label})` : ''}`
   *   console.error(
   *     `Error rendering SSG page with route ${pageId}${reason ? `: ${reason}` : ''}`
   *   )
   *   // Optional: exit the build process with an error code
   *   // If not exiting, the build will continue and accumulate errors then fail at the end.
   *   process.exit(1)
   * }
   *
   * @type OnSsgRendererError {@link OnSsgRendererError} {@link OnSsgRendererErrorFunction}
   * @default 'abort'
   */
  onSsgRendererError?: OnSsgRendererError;

  /**
   * The maximum number of SSG pages to render concurrently.
   * This can speed up rendering that includes asynchronous work, such as data fetching.
   * The render jobs run concurrently in the same Node.js thread.
   *
   * @default Math.max(1, os.availableParallelism() - 1)
   */
  ssgRendererConcurrency?: number;

  /**
   * The number of times for the SSG rendering process to retry
   * rendering a page if an error occurs during the SSG rendering process.
   *
   * @default 0
   */
  ssgRendererRetryCount?: number;

  /**
   * The delay in milliseconds between retries for the SSG rendering process.
   * This can help avoid overwhelming the system or external resources when retrying.
   *
   * @default 1000
   */
  ssgRendererRetryDelay?: number;

  /**
   * The name of the html file that will be used for the 404 page.
   * If set to false, no 404 page will be generated.
   *
   * You will need to properly configure the webserver to serve this
   * file for 404 errors.
   *
   * Make sure to name it so that the SSG generated html files
   * don't conflict with it!
   *
   * @default '404.html'
   */
  error404HtmlFilename?: string | false;

  /**
   * Configure this for a hybrid SSG + partial CSR (Client-Side Rendering)
   * build, where you want the client to use an empty shell html for some
   * of the pages (as if those pages are part of a SPA) and let the client-side
   * code take over and render the page.
   *
   * For production only. You will need to properly configure the webserver
   * to fallback to this html file for the pages that are not pre-rendered by SSG.
   *
   * Make sure to name it so that the SSG generated html files
   * don't conflict with it!
   *
   * If you are building a SSG+PWA app, you might want to directly use the
   * `pwaOfflineHtmlFilename` as the empty shell html file instead,
   * as it will have the same content. Otherwise, make sure to use a different
   * name otherwise it will clash with the `pwaOfflineHtmlFilename` one!
   *
   * If not explicitly configured and `clientSideRenderingRoutes`
   * is not its default value (an empty array), then this option will
   * default to 'csr.html'.
   *
   * @default false | 'csr.html'
   */
  clientSideRenderingHtmlFilename?: string | false;

  /**
   * Configure this for a hybrid SSG + partial CSR (Client-Side Rendering)
   * approach, where you have some Vue Router routes that you want to be
   * rendered on the client-side exclusively.
   *
   * When not also specifying `clientSideRenderingHtmlFilename`, the default
   * value for it becomes 'csr.html'.
   *
   * For production, you will need to properly configure the webserver
   * to fallback to the `clientSideRenderingHtmlFilename` for the pages that
   * are not pre-rendered by SSG.
   *
   * You can use picomatch patterns to match the routes you want to be rendered
   * on the client-side. https://www.npmjs.com/package/picomatch
   *
   * Note on picomatch patterns:
   *   "/admin" matches the exact route only,
   *   "/admin/**" matches the exact route and all sub-routes of /admin,
   *   "/admin/*" matches only direct sub-routes of /admin,
   *   "/admin/{users,settings}" matches both exact routes /admin/users and /admin/settings
   *
   * @example ['/dashboard', '/admin/**']
   * @default ssr.clientSideRenderingRoutes (when configured), otherwise []
   */
  clientSideRenderingRoutes?: string[];

  /**
   * Configure the Vue Router routes for which you don't want to inject
   * preload tags in the generated HTML by the SSG renderer process.
   *
   * You can use picomatch patterns to match the routes you want
   * no preload tags for. https://www.npmjs.com/package/picomatch
   *
   * Note on picomatch patterns:
   *   "/admin" matches the exact route only,
   *   "/admin/**" matches the exact route and all sub-routes of /admin,
   *   "/admin/*" matches only direct sub-routes of /admin,
   *   "/admin/{users,settings}" matches both exact routes /admin/users and /admin/settings
   *
   * @example ['/dashboard', '/admin/**']
   * @default ssr.noPreloadTagRoutes (when configured), otherwise []
   */
  noPreloadTagRoutes?: string[];

  /**
   * Extend the Rolldown config that is used for the SSG renderer,
   * which is your /src-ssg/ssg-renderer file.
   *
   * Can be async. Can directly modify the "config" parameter or
   * return a new one that will be merged with the default one.
   *
   * @type config {@link RolldownOptions}
   */
  extendSSGRendererConf?: (
    config: RolldownOptions
  ) => void | RolldownOptions | Promise<void | RolldownOptions>;

  /**
   * Extend the underlying SSR manifest file generated by Vite,
   * which is used by the server-side renderer to know which files to preload.
   *
   * Can be async. Can directly modify the "ssrManifest" parameter or
   * return a new one that will be merged with the default one.
   *
   * @type ssrManifest {@link QuasarSsrManifest}
   */
  extendSSGManifestJson?: (
    ssrManifest: QuasarSsrManifest
  ) => void | QuasarSsrManifest | Promise<void | QuasarSsrManifest>;

  /**
   * If a PWA should take over or just a SPA.
   * @default false
   */
  pwa?: boolean;

  /**
   * When using SSG+PWA, this is the name of the
   * PWA index html file that the client-side fallbacks to.
   *
   * Make sure to name it so that the SSG generated html files
   * don't conflict with it! Also, it shouldn't clash with the
   * "clientSideRenderingHtmlFilename" option if you are using that.
   *
   * @default ssr.pwaOfflineHtmlFilename (when configured), otherwise 'offline.html'
   */
  pwaOfflineHtmlFilename?: string;

  /**
   * Extend/configure the Workbox GenerateSW options
   * Specify Workbox options which will be applied on top of
   *  `pwa > extendPWAGenerateSWOptions()`.
   *
   * https://developer.chrome.com/docs/workbox/the-ways-of-workbox/
   *
   * Can be async. Can directly modify the "config" parameter or
   * return a new one that will be merged with the default one.
   *
   * @type config {@link GenerateSWOptions}
   */
  extendSSGGenerateSWOptions?: (
    config: GenerateSWOptions
  ) => void | GenerateSWOptions | Promise<void | GenerateSWOptions>;

  /**
   * Extend/configure the Workbox InjectManifest options
   * Specify Workbox options which will be applied on top of
   *  `pwa > extendPWAInjectManifestOptions()`.
   *
   * https://developer.chrome.com/docs/workbox/the-ways-of-workbox/
   *
   * Can be async. Can directly modify the "config" parameter or
   * return a new one that will be merged with the default one.
   *
   * @type config {@link InjectManifestOptions}
   */
  extendSSGInjectManifestOptions?: (
    config: InjectManifestOptions
  ) => void | InjectManifestOptions | Promise<void | InjectManifestOptions>;

  /**
   * Manually serialize the store state and provide it yourself
   * as window.__INITIAL_STATE__ to the client-side (through a <script> tag)
   * @default ssr.manualStoreSerialization (when configured), otherwise false
   */
  manualStoreSerialization?: boolean;

  /**
   * Manually inject the store state into ssrContext.state
   * @default ssr.manualStoreSsrContextInjection (when configured), otherwise false
   */
  manualStoreSsrContextInjection?: boolean;

  /**
   * Manually handle the store hydration instead of letting Quasar CLI do it.
   *
   * For Pinia: store.state.value = window.__INITIAL_STATE__
   *
   * @default ssr.manualStoreHydration (when configured), otherwise false
   */
  manualStoreHydration?: boolean;

  /**
   * Manually call $q.onSSRHydrated() instead of letting Quasar CLI do it.
   * This announces that client-side code should takeover.
   * @default ssr.manualPostHydrationTrigger (when configured), otherwise false
   */
  manualPostHydrationTrigger?: boolean;
}
