version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    working_directory: ~/quasar # directory where steps will run
    docker: # run the steps with Docker
      - image: circleci/node:10.14
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest pnpm'
      - run:
          name: install-npm-wee
          command: pnpm recursive install
      - run: # run tests
          name: test
          command: pnpm recursive test
workflows:
  version: 2
  workflow:
    jobs:
    - build