name: Bug report (Quasar v2)
description: Create a bug report to help us improve
labels: ['kind/bug', '🔝 Qv2']

# Note: Do NOT use commas(,) in options with 'multiple: true', the issue processing workflow won't be able to label it
body:
  - type: markdown
    attributes:
      value: |
        ### Read Before Proceeding Further

        This form is for submitting a **bug report** for Quasar Framework(**v2**).
        So, if you are using another version, just seeking help, or want to submit a feature request, please return back and choose a more suitable option from the list. 

        Also, please search your issue on the repo and make sure it does not already exist.

        Please fill out the form correctly according to the instructions, try to be as clear as possible, and provide as much as details you could provide, in order for our team to understand and resolve the issue easier and faster.
        Unclear or lacking information often results in issues to get resolved with high delays or even get closed.

        Thanks for your understanding, we truly appreciate your effort to fill out this form!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Clearly and concisely explain the problem.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: What did you expect to happen?
    validations:
      required: true
  - type: input
    id: repro-url
    attributes:
      label: Reproduction URL
      description: |
        Fork a [Codepen](https://codepen.quasar.dev) or a [jsFiddle](https://jsfiddle.quasar.dev) or a [Codesandbox](https://codesandbox.quasar.dev) and hit save then copy-paste the URL here.
        _You can provide a GitHub repo only as a last resort, keep in mind that it will be prioritized less as it makes the repro process slower._
      placeholder: https://codepen.io/rstoenescu/pen/xxEvBLR
    validations:
      required: true
  - type: textarea
    id: repro-description
    attributes:
      label: How to reproduce?
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to the provided reproduction link
        2. Click on '....'
        3. Scroll down to '....'
        4. See the error
    validations:
      required: true
  - type: dropdown
    id: flavour
    attributes:
      label: Flavour
      description: Choose the Quasar flavour you are using. _The names between parentheses indicate the package names if applicable._
      options:
        - Quasar CLI (@quasar/cli | @quasar/app)
        - UMD
        - Vite Plugin (@quasar/vite-plugin)
        - Vue CLI Plugin (vue-cli-plugin-quasar)
    validations:
      required: true
  - type: dropdown
    id: areas
    attributes:
      label: Areas
      description: Mark the areas in which you see the problem on. _The names between parentheses indicate the package names if applicable._
      multiple: true
      options:
        - Quasar CLI Commands/Configuration (@quasar/cli | @quasar/app)

        - Components (quasar)
        - Directives (quasar)
        - Plugins (quasar)
        - Composables (quasar)
        - Style & Identity (quasar)

        - Quasar Extras (@quasar/extras)
        - TypeScript Support
        - App Extension API
        # TODO: Consider creating a separate issue template for Icon Genie CLI as most of the info requested may not be relevant
        - Icon Genie CLI (@quasar/icongenie)

        - SPA Mode
        - SSR Mode
        - PWA Mode
        - Electron Mode
        - Cordova Mode
        - Capacitor Mode
        - BEX Mode
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: Platforms/Browsers
      description: Mark the platforms/browsers in which you see the problem on. _If you select `Other`, please explain it in `Additional context` section._
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - iOS
        - Android
        - Electron
        - Other
  - type: textarea
    id: q-info
    attributes:
      label: Quasar info output
      description: |
        Please run [`quasar info` command](https://quasar.dev/quasar-cli/commands-list#info), then copy and paste the output.
        _This will be automatically formatted into code, so no need for backticks._
      render: shell
    # TODO: Validate the format by using GitHub Actions, Probot, etc.
    # TODO: Make this required if the flavour is Quasar CLI, by using GitHub Actions, Probot, etc.
    # Consider adding separate controls to select important versions such as quasar, @quasar/app, vite, etc. to also respect the other flavours
    # or add just the 'quasar' version(to cover UMD), then evolve `quasar info` command to cover most/all cases, and make people use `npx quasar info` for the environment and package information
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: |
        Please copy and paste any relevant log output.
        _This will be automatically formatted into code, so no need for backticks._
      render: shell
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
