name: Docs report
description: Unclear, missing or wrong content on quasar.dev
labels: ['kind/docs 📄']

body:
  - type: markdown
    attributes:
      value: |
        ### Read Before Proceeding Further

        This form is for submitting a **docs report** for [quasar.dev](https://quasar.dev).
        If you are just seeking help or would like to submit a feature request, go back and choose a more suitable option from the list.

        Also, search for your issue in the repo to be sure it doesn't exist already.

        To enter your issue, fill out the form correctly and according to the instructions. Try to be as clear as possible and provide as many details as possible, to help our team better understand the issue and to resolve it faster.
        Issues with an unclear description or lacking information will have a lower priority. They may even get closed without taking action.

        Lastly, read the [Contributing to the Quasar Documentation | Contribution Guide](https://quasar.dev/how-to-contribute/contribution-guide#contributing-to-the-quasar-documentation) section of our docs for a more detailed explanation.

        Thanks for your understanding. We truly appreciate your effort to fill out this form!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Clearly and concisely explain the problem.
        You can mention unclear or missing information, typos, grammatical mistakes, etc.
        Any contributions and suggestions are welcome!
    validations:
      required: true
  - type: input
    id: docs-page-url
    attributes:
      label: Documentation Section URL
      description: If the problem is related to an existing docs page/section, click the related section's title and paste the URL here.
      placeholder: https://quasar.dev/vue-components/table#virtual-scrolling
