import { defineSsgGetPages, defineSsgRenderPreloadTag } from '#q-app';
<% if (!scope.filenameBasedRouting) { %>
import routes from '@/router/routes';
<% } %>

/**
 * Return an Array of pages to be generated by SSG.
 * The function passed to defineSsgGetPages can be async.
 *
 * Each page is an Object with the following properties:
 *
 *  The vue-router route to render.
 *  It must be a valid route in your Vue Router configuration.
 *  route: string;
 *
 *  Optional label to identify the SSG page in logs.
 *  label?: string;
 *
 *  Optional directory to place the generated HTML file in.
 *  Must use relative path to the dist folder.
 *  It will be joined with the quasar.config > build > distDir.
 *  If not provided, the route will be used to determine the directory.
 *  dir?: string;
 *
 *  Optional filename to use for the generated HTML file.
 *  Default value: 'index.html'
 *  filename?: string;
 *
 *  Optional SSR context to use when rendering the page.
 *  If not provided, the default SSR context will be used.
 *  ssrContext?: SsgPageSsrContext;
 *
 * You can use the `ctx` parameter to access appPaths, among
 * other things, to help you resolve paths to your pages then
 * use packages like tinyglobby.
 */
<% if (scope.filenameBasedRouting) { %>
export const getSsgPages = defineSsgGetPages(
  async ({ getFilenameBasedRoutes, parseVueRouterRoutes }) => {
    const routes = await getFilenameBasedRoutes();

    // The use of parseVueRouterRoutes is optional as it's just a helper function.
    const { ssgPages } = parseVueRouterRoutes({ routes, verbose: true });

    return ssgPages;
  }
);
<% } else { %>
export const getSsgPages = defineSsgGetPages(({ parseVueRouterRoutes }) => {
  // The use of parseVueRouterRoutes is optional as it's just a helper function.
  const { ssgPages } = parseVueRouterRoutes({ routes, verbose: true });

  return ssgPages;
});
<% } %>

const jsRE = /\.js$/
const cssRE = /\.css$/
const woffRE = /\.woff$/
const woff2RE = /\.woff2$/
const gifRE = /\.gif$/
const jpgRE = /\.jpe?g$/
const pngRE = /\.png$/

/**
 * Should return a String with HTML output
 * (if any) for preloading indicated file
 */
export const renderPreloadTag = defineSsgRenderPreloadTag(
  (file /* , { ssrContext } */) => {
    if (jsRE.test(file)) {
      return `<link rel="modulepreload" href="${file}" crossorigin>`;
    }

    if (cssRE.test(file)) {
      return `<link rel="stylesheet" href="${file}" crossorigin>`;
    }

    if (woffRE.test(file)) {
      return `<link rel="preload" href="${file}" as="font" type="font/woff" crossorigin>`;
    }

    if (woff2RE.test(file)) {
      return `<link rel="preload" href="${file}" as="font" type="font/woff2" crossorigin>`;
    }

    if (gifRE.test(file)) {
      return `<link rel="preload" href="${file}" as="image" type="image/gif" crossorigin>`;
    }

    if (jpgRE.test(file)) {
      return `<link rel="preload" href="${file}" as="image" type="image/jpeg" crossorigin>`;
    }

    if (pngRE.test(file)) {
      return `<link rel="preload" href="${file}" as="image" type="image/png" crossorigin>`;
    }

    return '';
  }
);
