import { defineConfig } from 'vitest/config'

export default defineConfig({
  test: {
    // /test hosts the e2e suite exclusively (unit tests are colocated
    // with their sources under /src); it serves the monorepo's own
    // ui and app-vite slices, generated by the pretest:e2e hook
    include: ['./test/*.test.js'],
    reporters: 'verbose'
  }
})
