import { existsSync, readFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'

/**
 * The packages that ship a docs slice in `dist/mcp`, in the order the
 * server lists them. The slices are generated by the docs site build
 * (`docs/build/mcp`, `--target`) as the last step of each package's
 * `prepublishOnly`.
 */
export const DOCS_PACKAGES = ['quasar', '@quasar/app-vite']

/**
 * The first releases that bundle their docs slice; older installs
 * serve nothing but the ui API JSON, which every quasar release ships.
 */
export const BUNDLED_DOCS_SINCE = {
  quasar: '2.33.0',
  '@quasar/app-vite': '3.9.0'
}

/**
 * @typedef {object} InstalledPackage
 * @property {string} name
 * @property {string} version
 * @property {string} dir The package root inside the project's node_modules.
 * @property {string | null} docsDir `dist/mcp` when this release bundles its docs.
 * @property {string | null} apiDir `dist/api` for quasar (the component/plugin/directive JSON descriptors).
 */

/**
 * @typedef {object} Project
 * @property {string} dir
 * @property {InstalledPackage[]} packages The DOCS_PACKAGES the project has installed.
 */

/**
 * The package as the project's own code would resolve it: the nearest
 * `node_modules/<name>` walking up from the project, so a pnpm strict
 * layout, a hoisted one and a workspace link all land on the copy the
 * project runs. Symlinks are kept as found: the files read the same
 * through them.
 *
 * @param {string} projectDir
 * @param {string} name
 * @returns {InstalledPackage | null}
 */
function locatePackage(projectDir, name) {
  let dir = null
  for (
    let current = projectDir, parent = dirname(current);
    dir === null;
    current = parent, parent = dirname(current)
  ) {
    const candidate = join(current, 'node_modules', name)
    if (existsSync(join(candidate, 'package.json'))) {
      dir = candidate
    } else if (parent === current) {
      return null
    }
  }

  const packageJsonPath = join(dir, 'package.json')
  const { version } = JSON.parse(readFileSync(packageJsonPath, 'utf8'))
  const docsDir = join(dir, 'dist', 'mcp')
  const apiDir = join(dir, 'dist', 'api')

  return {
    name,
    version,
    dir,
    docsDir: existsSync(join(docsDir, 'meta.json')) ? docsDir : null,
    apiDir: name === 'quasar' && existsSync(apiDir) ? apiDir : null
  }
}

/**
 * @param {string} [projectDir] Defaults to the current working directory.
 * @returns {Project}
 */
export function loadProject(projectDir = process.cwd()) {
  const dir = resolve(projectDir)
  const packages = []
  for (const name of DOCS_PACKAGES) {
    const installed = locatePackage(dir, name)
    if (installed !== null) {
      packages.push(installed)
    }
  }
  return { dir, packages }
}
