// THIS FEATURE-FLAG FILE IS AUTOGENERATED,
//  REMOVAL OR CHANGES WILL CAUSE RELATED TYPES TO STOP WORKING
import "quasar";

declare module "quasar" {
  interface QuasarFeatureFlags {
    capacitor: true;
  }
}
